### ISSUE TITLE
Add Docker Integration

### ISSUE THREAD

**Issue by omarabid** [omarabid/rust-starter#3]
Add Docker build files

**Goals**:

Be able to use Docker to compile and run the program for development purposes.
Use the Docker setup to mimic an offline environment of the circleci test machine.

**Todo List**:

- [x]  Docker image names should be automatically unique (instead of having to replace rust-starter).
- [ ]  The circle-ci commands actually fails in some circumstances.
- [x]  Preferably the .dockerignore file should be in the docker directory.

**Comment by omarabid** [comment]
Goals:

- Be able to use Docker to compile and run the program for development purposes.
- Use the Docker setup to mimic an offline environment of the circleci test machine.

**Comment by omarabid** [comment]
Will be moving from CircleCi to Travis/AppVeyor
